### ISSUE TITLE
 requirements.txt cffi version doesn't get installed with python3.8

### ISSUE THREAD

**Issue by Ganeshbg** [CiscoDevNet/Getting-started-with-Cisco-SD-WAN-REST-APIs#14]
Hey

I got the below error while trying to install cffi with pip

```
Collecting cffi==1.11.5 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/gbyrandu/cisco/Getting-started-with-Cisco-SD-WAN-REST-APIs/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/setup.py", line 141, in <module>
        use_pkg_config()
      File "/private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/setup.py", line 104, in use_pkg_config
        _ask_pkg_config(include_dirs,       '--cflags-only-I', '-I', sysroot=True)
      File "/private/var/folders/xk/78r3xfp50ndg205zszg4xzlr0000gn/T/pip-install-7hjsncow/cffi/setup.py", line 23, in _ask_pkg_config
        p = subprocess.Popen([pkg_config, option, 'libffi'],
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    NotADirectoryError: [Errno 20] Not a directory: 'pkg-config'
```

I changed the cffi verison to the latest one and it worked fine, I guess READme need a fix.

**Comment by x0velin** [comment]
Same issue (python 3.8 too) and setting cffi version to 1.14.4 works fine ! Thank you very much @Ganeshbg

**Comment by brwnie** [comment]
Same error in Ubuntu 20.04.3 LTS
