### ISSUE TITLE
Issue with ./sdwan.py script

### ISSUE THREAD

**Issue by pynas67** [CiscoDevNet/Getting-started-with-Cisco-SD-WAN-REST-APIs#24]
$ ./sdwan.py 
Traceback (most recent call last):
  File "C:\Users\pynas\OneDrive\Desktop\Getting-started-with-Cisco-SD-WAN-REST-APIs\sdwan.py", line 19, in <module>
    import tabulate
  File "C:\Users\pynas\OneDrive\Desktop\Getting-started-with-Cisco-SD-WAN-REST-APIs\venv\Lib\site-packages\tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Python311\Lib\collections\__init__.py)

hello folks i am new to Python and trying to follow the code as it is written in getting started with sdwan but i am having this output not sure how to fix it.

Thank you!

**Comment by pynas67** [comment]
I did comment the line 19 and it seems to work however not sure how it will affect the code itself. any help will be appreciated. Thank you!
